Add a parameter to bartender to specify where the temp dir should be
chrisglass/ubuntu-old-fashioned pull request #55
Opened 2020-08-20 23:05 UTC by codyshepherd

2020-11-02 20:26 UTC, rcj4747 requested changes
Looks like you missed an update when changing from $HOME to $TMP_DIR_LOC

2020-11-02 20:26 UTC, rcj4747 commented on scripts/ubuntu-bartender/ubuntu-bartender
> +                                            Value: $HOME
Should be `Value: $TMP_DIR_LOC` now, right?

2020-11-13 15:34 UTC, codyshepherd commented
Good catch @rcj4747. Fix pushed.

2020-11-16 20:39 UTC, davidkrauser approved these changes

2020-11-16 20:42 UTC, merged